# Generated by Django 5.2.3 on 2025-06-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_task_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
